# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DetectionErreursLidar
                                 A QGIS plugin
 Ce plugin détecte les points de classe sol déclassés par erreur.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-03-15
        copyright            : (C) 2023 by Lubin, Ibtissam, Judith, Estelle
        email                : estellounette@ensg.eu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Lubin, Ibtissam, Judith, Estelle'
__date__ = '2023-03-15'
__copyright__ = '(C) 2023 by Lubin, Ibtissam, Judith, Estelle'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DetectionErreursLidar class from file DetectionErreursLidar.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .detection_erreur_lidar import DetectionErreursLidarPlugin
    return DetectionErreursLidarPlugin()
